version: '3.7'

services:

  web:
    build : ./src
    container_name : web-nosql
    command: python app.py
    restart: unless-stopped
    volumes : 
      - ./src:/usr/src/app
    ports :
      - 8080:80
    
  postgres:
    container_name: postgres-nosql
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    image: postgres:alpine
    ports:
    - 5432:5432
    volumes:
    - "./bdd/data:/var/lib/postgresql/data"
    - "./src/postgre/script_creation.sql:/docker-entrypoint-initdb.d/script_creation.sql"


  mongodb:
    image: mongo
    container_name: mongo-nosql
    volumes:
      - ./bdd/mongo:/data/db
    hostname: 'mongodb'
    ports:
      - 27017-27019:27017-27019

    
    